apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-vault-agent-config
  namespace: default
data:
  vault-agent-config.hcl: |
    # Comment out or delete below line if running as sidecar instead of initContainer
    exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "example"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    # # Spring Boot properties templating example
    template {
    destination = "/etc/secrets/application-secret.yml"
    contents = <<EOT
    {{- with secret "secret/data/myapp/config" }}
    vault.secret.user: {{ .Data.data.username }}
    vault.secret.password: {{ .Data.data.password }}
    vault.secret.othersecret: {{ .Data.data.othersecret }}
    {{ end }}
    EOT
    }

