apiVersion: v1
kind: Service
metadata:
  name: hello-vault
  labels:
    app: hello-vault
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 8889
      targetPort: 8889
  selector:
    app: hello-vault
